[project]
name = "morado"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "allure-pytest>=2.15.2",
    "litestar>=2.19.0",
    "playwright>=1.57.0",
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
    "pytest-rerunfailures>=16.1",
    "requests>=2.32.5",
    "ruff>=0.14.9",
    "selenium>=4.39.0",
    "uvicorn>=0.38.0",
]
