[project]
name = "morado"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "allure-pytest>=2.15.2",
    "httpx>=0.28.1",
    "jsonpath-ng>=1.7.0",
    "litestar>=2.19.0",
    "msgspec>=0.20.0",
    "orjson>=3.11.5",
    "playwright>=1.57.0",
    "pydantic>=2.12.5",
    "pytest>=9.0.2",
    "pytest-asyncio>=1.3.0",
    "pytest-cov>=7.0.0",
    "pytest-rerunfailures>=16.1",
    "pytest-xdist>=3.8.0",
    "python-dotenv>=1.2.1",
    "redis>=7.1.0",
    "requests>=2.32.5",
    "ruff>=0.14.9",
    "schemathesis>=4.7.6",
    "selenium>=4.39.0",
    "sqlalchemy>=2.0.45",
    "structlog>=25.5.0",
    "taskiq>=0.12.1",
    "tenacity>=9.1.2",
    "uvicorn>=0.38.0",
]
